"use client"
/* eslint-disable @typescript-eslint/no-explicit-any */
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _student_dashboard from './student-dashboard.bones.json'
import _student_logbook from './student-logbook.bones.json'
import _student_opportunities from './student-opportunities.bones.json'
import _student_documents from './student-documents.bones.json'
import _student_completion from './student-completion.bones.json'
import _employer_dashboard from './employer-dashboard.bones.json'
import _employer_applicants from './employer-applicants.bones.json'
import _employer_evaluations from './employer-evaluations.bones.json'
import _employer_logbooks from './employer-logbooks.bones.json'
import _employer_postings from './employer-postings.bones.json'
import _coordinator_dashboard from './coordinator-dashboard.bones.json'
import _coordinator_companies from './coordinator-companies.bones.json'
import _coordinator_placements from './coordinator-placements.bones.json'
import _coordinator_registrations from './coordinator-registrations.bones.json'
import _coordinator_reports from './coordinator-reports.bones.json'
import _coordinator_students from './coordinator-students.bones.json'

registerBones({
  "student-dashboard": _student_dashboard as any,
  "student-logbook": _student_logbook as any,
  "student-opportunities": _student_opportunities as any,
  "student-documents": _student_documents as any,
  "student-completion": _student_completion as any,
  "employer-dashboard": _employer_dashboard as any,
  "employer-applicants": _employer_applicants as any,
  "employer-evaluations": _employer_evaluations as any,
  "employer-logbooks": _employer_logbooks as any,
  "employer-postings": _employer_postings as any,
  "coordinator-dashboard": _coordinator_dashboard as any,
  "coordinator-companies": _coordinator_companies as any,
  "coordinator-placements": _coordinator_placements as any,
  "coordinator-registrations": _coordinator_registrations as any,
  "coordinator-reports": _coordinator_reports as any,
  "coordinator-students": _coordinator_students as any,
})
