"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _student_dashboard from './student-dashboard.bones.json'
import _student_logbook from './student-logbook.bones.json'
import _student_opportunities from './student-opportunities.bones.json'
import _student_documents from './student-documents.bones.json'
import _student_completion from './student-completion.bones.json'
import _employer_dashboard from './employer-dashboard.bones.json'
import _employer_applicants from './employer-applicants.bones.json'
import _employer_evaluations from './employer-evaluations.bones.json'
import _employer_logbooks from './employer-logbooks.bones.json'
import _employer_postings from './employer-postings.bones.json'
import _coordinator_dashboard from './coordinator-dashboard.bones.json'
import _coordinator_companies from './coordinator-companies.bones.json'
import _coordinator_placements from './coordinator-placements.bones.json'
import _coordinator_registrations from './coordinator-registrations.bones.json'
import _coordinator_reports from './coordinator-reports.bones.json'
import _coordinator_students from './coordinator-students.bones.json'

registerBones({
  "student-dashboard": _student_dashboard,
  "student-logbook": _student_logbook,
  "student-opportunities": _student_opportunities,
  "student-documents": _student_documents,
  "student-completion": _student_completion,
  "employer-dashboard": _employer_dashboard,
  "employer-applicants": _employer_applicants,
  "employer-evaluations": _employer_evaluations,
  "employer-logbooks": _employer_logbooks,
  "employer-postings": _employer_postings,
  "coordinator-dashboard": _coordinator_dashboard,
  "coordinator-companies": _coordinator_companies,
  "coordinator-placements": _coordinator_placements,
  "coordinator-registrations": _coordinator_registrations,
  "coordinator-reports": _coordinator_reports,
  "coordinator-students": _coordinator_students,
})
